#+TITLE: Streak

This Emacs Lisp package provides =streak-mode=, a minor mode for tracking some
daily streak. Exercising? Learning a language? Track your success in your mode
line!

* Installation

*Note: this package requires at least Emacs 27.1*

** Vanilla Emacs

This package is not yet available on Elpa/Melpa. It can be cloned from GitHub
and installed with ~package-install-file~ as follows:

First, clone the repository:

#+begin_src shell
git clone https://github.com/fosskers/streak.git
#+end_src

Then, from within Emacs:

+ ~M-x package-install-file~
+ Select =streak.el= from the git repo cloned above
+ If needed: ~M-x package-initialize~
+ ~M-x stream-mode~

** Doom Emacs

Place the following in your =packages.el=:

#+begin_src elisp
(package! streak
  :recipe (:host github :repo "fosskers/streak"))
#+end_src

And make sure to run =doom sync -u=. Then in your =config.el=:

#+begin_src elisp
(require 'streak)
(streak-mode)
#+end_src

This will start =streak-mode= upon startup.

* Usage

=streak-mode= will automatically initialize the "streak file" the first time it is
ran. Once you've started a streak, it will increment (in the mode line)
automatically day by day.

Otherwise, consider these functions for more manual control:

+ =streak-reset=: Reset your streak, with "now" as the new starting point.
+ =streak-increment=: Increase your streak by 24 hours worth.
+ =streak-decrement=: The opposite of the above.
+ =streak-update=: Reread the streak file and manually update the mode line.
